export enum ActionsConstant {
    APP_STATE_VEHICLE = 'vehicle',
    GET_ALL_VEHICLE = 'getAllVehicle',
    APP_STATE_VIEW = 'view',
    SET_CURRENT_MODULE = 'setCurrentModule',
    SET_MODULE_NAME = 'setModuleName',
    SET_MODULE_REF = 'setModuleRef',
    GET_ALL_VEHICLE_COUNT = 'getAllRangeVehicleCount',
    SET_API_LOADER = 'setApiLoader',
    GET_UPDATED_VEHICLE_COUNT = 'getUpdatedVehicleCount',
    SET_ALERT_CONFIG = 'setAlertConfig',
    RESET_VEHICLE_COUNT = 'resetVehicleCount',
    SET_CARD_DETAILS_VIEW = 'setCardDetailsView',
    SET_FILTERS_CONFIG = 'filtersConfig',
    SET_FILTER = 'setFilter',
    SET_FILTER_QUERY_STRING = 'setFilterQueryString',
    SET_EXCEPTION = 'setException',
    SET_VEHICLE_API_DETAILS = 'vehicleApiDetails',
    GET_RANGE_VEHICLE_COUNT = 'getSelectedRangeVehicleCount',
    RESET_RANGE_VEHICLE_COUNT = 'resetRangeVehicleCount',
    SET_EXPAND_ALL_FOR_ROWS = 'setExpandAllForRows',
    SET_COLLAPSE_ON_PAGE_FILTER = 'setCollapseOnPageFilter',
    SET_EXPAND_FOR_SINGLE_ROW = 'setExpandForSingleRow',
    SET_EXPORT_TYPE = 'setExportType'
}
